DROP DATABASE IF EXISTS FitGen;

CREATE DATABASE FitGen;
USE FitGen;

CREATE TABLE User(
uID INT PRIMARY KEY,
name VARCHAR(50),
email VARCHAR(50),
password VARCHAR(250),
age INT,
sex CHAR
);

CREATE TABLE ExercisePlan(
epID INT,
uID INT,
month VARCHAR(10),
year INT,
PRIMARY KEY(epID, uID),
FOREIGN KEY(uID) REFERENCES User(uID)
);

CREATE TABLE Exercise(
eID INT PRIMARY KEY,
eName VARCHAR(100),
eDesc VARCHAR(500),
type VARCHAR(100)
);

CREATE TABLE WORKOUT(
epID INT,
eID INT,
date DATE,
focus VARCHAR(100),
PRIMARY KEY (epID, date),
FOREIGN KEY (epID) REFERENCES ExercisePlan(epID),
FOREIGN KEY (eID) REFERENCES Exercise(eID)
);